/*
 * MainForm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.wasoft.dataserver.gui;

import java.io.PipedReader;
import java.io.PipedWriter;
import java.io.Writer;
import java.util.Scanner;
import javax.swing.text.DefaultCaret;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.log4j.Appender;
import org.apache.log4j.Logger;
import org.apache.log4j.WriterAppender;
import com.wasoft.dataserver.DataServer;

/**
 * 
 * @author __USER__
 */
@SuppressWarnings("serial")
public class MainForm extends javax.swing.JFrame {
	private static final Log log = LogFactory.getLog(MainForm.class);

	private static StringBuffer stdout = new StringBuffer();

	/** Creates new form MainForm */
	public MainForm() {

		initComponents();
		DefaultCaret caret = (DefaultCaret) jTextAreaLog.getCaret();
		caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

		// System.setOut(new GUIPrintStream(System.out, jTextAreaLog));
		setWriterAppender();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldPort = new javax.swing.JTextField();
		jButtonServer = new javax.swing.JButton();
		jButtonClearLog = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButtonSend = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		ServerName = new javax.swing.JTextField();
		ServerPort = new javax.swing.JTextField();
		cmd = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextAreaLog = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u901a\u8baf\u6d4b\u8bd5");

		jLabel1.setText("\u670d\u52a1\u7aef\u53e3");

		jTextFieldPort.setText("3001");

		jButtonServer.setText("\u542f \u52a8");
		jButtonServer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonServerActionPerformed(evt);
				// jButton1ActionPerformed(evt);
			}
		});

		jButtonClearLog.setText("\u6e05\u9664\u65e5\u5fd7");
		jButtonClearLog.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonClearLogActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextFieldPort,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												52,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButtonServer)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												482, Short.MAX_VALUE)
										.addComponent(jButtonClearLog)
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.CENTER)
														.addComponent(jLabel1)
														.addComponent(
																jTextFieldPort,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButtonServer,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButtonClearLog))
										.addContainerGap(22, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u670d\u52a1\u7aef", jPanel1);

		jButtonSend.setText("\u4ea4\u6613\u8bf7\u6c42");
		jButtonSend.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jButtonSendActionPerformed(evt);
			}
		});

		jLabel2.setText("\u670d\u52a1\u5668");

		jLabel3.setText("\u7aef\u53e3");

		jLabel4.setText("\u4ea4\u6613\u7801");

		ServerName.setText("127.0.0.1");

		ServerPort.setText("1111");

		cmd.setText("202");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												ServerName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												135,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												ServerPort,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												44,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												cmd,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButtonSend)
										.addContainerGap(322, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButtonSend)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(
																ServerName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																cmd,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																ServerPort,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(22, Short.MAX_VALUE)));

		jButtonSend.getAccessibleContext().setAccessibleName("");

		jTabbedPane1.addTab("\u5ba2\u6237\u7aef", jPanel2);

		jTextAreaLog.setColumns(20);
		jTextAreaLog.setRows(5);
		jScrollPane1.setViewportView(jTextAreaLog);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761,
				Short.MAX_VALUE).addComponent(jScrollPane1,
				javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												84,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												417, Short.MAX_VALUE)
										.addContainerGap()));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	// 清除日志
	private void jButtonClearLogActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		stdout.setLength(0);
		jTextAreaLog.setText(stdout.toString());
	}

	// 启动服务
	private void jButtonServerActionPerformed(java.awt.event.ActionEvent evt) {
		DataServer.GuiStart();
		jButtonServer.setEnabled(false);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

	public void setWriterAppender() {
		Logger root = Logger.getRootLogger();
		try {
			// 需要在log4j.properties开启WriterAppender
			Appender appender = root.getAppender("WriterAppender");
			PipedReader reader = new PipedReader();
			Writer writer = new PipedWriter(reader);

			((WriterAppender) appender).setWriter(writer);

			(new ScanThread(reader)).start();
		} catch (Exception e) {
			log.error(e.getMessage());
		}
	}

	class ScanThread extends Thread {
		PipedReader reader;

		public ScanThread(PipedReader reader) {
			this.reader = reader;
		}

		public void run() {
			Scanner scanner = new Scanner(reader);
			while (scanner.hasNext()) {
				stdout.append(scanner.nextLine()).append("\r\n");
				jTextAreaLog.setText(stdout.toString());
			}
		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField ServerName;

	private javax.swing.JTextField ServerPort;

	private javax.swing.JTextField cmd;

	private javax.swing.JButton jButtonClearLog;

	private javax.swing.JButton jButtonSend;

	private javax.swing.JButton jButtonServer;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;

	private javax.swing.JLabel jLabel3;

	private javax.swing.JLabel jLabel4;

	private javax.swing.JPanel jPanel1;

	private javax.swing.JPanel jPanel2;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JTabbedPane jTabbedPane1;

	private javax.swing.JTextArea jTextAreaLog;

	private javax.swing.JTextField jTextFieldPort;
	// End of variables declaration//GEN-END:variables

}